dataset:
  name: pennfudan
  root: data/datasets/PennFudanCOCO
  train_images: train/images
  val_images: val/images
  train_annotations: annotations/train.json
  val_annotations: annotations/val.json
